spring.application.name=api

spring.datasource.url=jdbc:sqlite:C:/SQLite_Projects/PedeJa.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=com.pedeja.api.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true